### ISSUE TITLE
Webpack Config seems incompatible with dependency update

### ISSUE THREAD

**Issue by scrobert** [craftcms/starter-blog#139]
### Description

Hi, 

just played around with your project a little. I noticed that the updates regarding the npm dependencies seem to have introduced several issues with the webpack configuration. 

It seems webpack-dev-server reworked their configuration API and the webpack.config.js in your project doesn't support webpack-dev-server 4.0.0 and above

### Steps to reproduce

1. run `npm install`
2. run `npm run hot`

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by mattstein** [comment]
Thanks @scrobert! Just updated that configuration and things are working again.
