### ISSUE TITLE
Gatsby build inlines css

### ISSUE THREAD

**Issue by samhernandez** [craftcms/starter-blog#2]
After running `gatsby build`, generated HTML files have all styles inlined.

**Comment by mattstein** [comment]
Closing since this is no longer the case. Styles are chunked and included as expected and markup looks good. Only inline styles are for the `#gatsby-announcer` that [gets injected for accessibility](https://www.gatsbyjs.com/blog/2020-02-10-accessible-client-side-routing-improvements/).
