### ISSUE TITLE
Issues with ddev craft up

### ISSUE THREAD

**Issue by mateostabio** [craftcms/starter-blog#208]
### Description
I just tried to install this starter-blog, but as soon as I get to the ddev craft up instruction, I'd like to see the demo site with fake content, but it seems to throw this error.
```
ddev craft up
🔒 Acquiring lock ... done

Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.

Checking for pending content migrations ...
Total 1 new migration to be applied:
	m210104_175929_sample_content

Apply the above migration? (yes|no) [no]:yes
*** applying m210104_175929_sample_content
Blog section does not exist.*** failed to apply m210104_175929_sample_content (time: 0.049s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
🔓 Releasing lock ... done
Failed to run craft up: exit status 1
```

### Additional info

- Craft version: 4.4.5
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by AugustMiller** [comment]
Hi! Thanks for reporting.

I believe I've fixed the issue that was causing the bundled project config data to be discarded during installation. (When [making updates last month](https://github.com/craftcms/starter-blog/pull/203), I must have missed the [updated `system.schemaVersion` setting](https://github.com/craftcms/starter-blog/commit/60dde979bbcb51d4f317b825caa4955e309cef30#diff-7e3956121cbdc105437f5f8c5f707c8d788f35349996a5adab4a503ff3a977b9L70-R70)!)

If you're able:

- Run `ddev delete` to tear down the current environment and database (DDEV will capture a backup before doing this);
- Remove the `vendor/` directory (for good measure);
- Follow the setup guide again;
- Apply the migrations with `ddev craft up`;

This ought to produce a working installation! If not, ping me here and we'll get you sorted. 💕
