### ISSUE TITLE
Project Config does not match latest version of Craft

### ISSUE THREAD

**Issue by aldisaglobal** [craftcms/starter-blog#212]
### Description
The project config and data migration included with the package do not get installed because the Craft Schema version specified in project config does not match the latest package installed by Composer (4.5.0.3).  See following excerpt from the output of the `craft setup` command.

````
    > can't apply existing project config: Craft is installed at the wrong schema version (4.5.0.3, but project.yaml lists 4.4.0.4).
    > moving config/project/ to storage/config-backups/project-2023-08-25-153549 ... done
````

After this, the Craft instance is lacking all the Blog related settings and the sample data migration fails to load as well.

### Steps to reproduce

1.  Git Clone Repo
2.  Composer Update
3.  Run Setup

### Additional info

- Craft version: 4.5.0.3
- PHP version:  8.1.
- Database driver & version:  MySQL 8.0.30
- Plugins & versions:  only what is included in repo

**Comment by AugustMiller** [comment]
Somehow, these got out of sync! I've gone and re-applied updates, so the setup wizard should accept the provided Project Config files. 🤞
