### ISSUE TITLE
Gatsby fails in headless folder with various errors

### ISSUE THREAD

**Issue by sijones-uk** [craftcms/starter-blog#30]
### Description

Running `gatsby develop` in the `headless-front-end/gatsby` folder fails with a bunch of errors, starting with this:

```
Cannot query field "allCraftBlogBlogEntry" on type "Query".
```

This is followed by these errors:

```
Unknown type "Craft_bodyContent_richText_BlockType".
Unknown type "Craft_bodyContent_quote_BlockType".
Unknown type "Craft_uploads_Asset".
Unknown type "Craft_bodyContent_imageCarousel_BlockType".
Unknown type "Craft_uploads_Asset".
Unknown type "Craft_bodyContent_embed_BlockType".
```

This is running Gatsby in Windows 10, with Craft running in Homestead.

### Steps to reproduce

1. Follow steps to install the Starter Blog in the README
2. cd to `headless-front-end/gatsby` folder and type `gatsby develop`

### Additional info

- OS: Windows 10
- Craft version: 3.5.15.1
- PHP version: 7.4
- Database driver & version: MySQL driver (MariaDB 10.4.12)
- Plugins & versions:

  **Craft plugins:**
  Asset Rev: 6.0.2
  Gatsby Helper: dev-master
  Redactor: 2.8.3
  Typogrify: 1.1.18
  oEmbed: 1.3.6

  **npm packages:**
  gatsby: ^2.25.3,
  gatsby-image: ^2.4.21,
  gatsby-plugin-manifest: ^2.5.2,
  gatsby-plugin-offline: ^2.2.7,
  gatsby-plugin-react-helmet: ^3.3.13,
  gatsby-plugin-sass: ^2.4.2,
  gatsby-plugin-sharp: ^2.7.1,
  gatsby-source-craft: ^1.0.0-beta.1,
  gatsby-source-filesystem: ^2.4.1,
  gatsby-transformer-sharp: ^2.5.17,
  nuka-carousel: ^4.7.1,
  prop-types: ^15.7.2,
  react: ^16.13.1,
  react-dom: ^16.13.1,
  react-helmet: ^5.2.1,
  snyk: ^1.424.4

**Comment by mattstein** [comment]
Sorry @sijones-uk, looks like this project’s [Gatsby readme](https://github.com/craftcms/starter-blog/tree/master/headless-front-end/gatsby) needs updating.

The configuration is slightly different using the just-released plugins: https://github.com/craftcms/gatsby-source-craft#quick-start

Guessing the tl;dr is update your environment variable names...

```
CRAFTGQL_TOKEN=your-graphql-token
CRAFTGQL_URL=https://your-craftcms-site.test/api
```

...and enable **Allow discovery of sourcing data for Gatsby** for your schema after the [Gatsby Helper](https://github.com/craftcms/gatsby-helper) is installed if you’ve not already done that.

Can you let me know if that does it?

**Comment by sijones-uk** [comment]
Unfortunately, I'm still getting the same errors. I'd already create a `.env` with the `CRAFTGQL_TOKEN` and `CRAFTGQL_URL` variables in (I also tried changing the filename to `.env.development` as per the [Gatsby documentation](https://www.gatsbyjs.com/docs/environment-variables/#client-side-javascript), without any success). I tried regenerating the token to be certain it wasn't that, and it didn't make any difference. (I set the `CRAFTGQL_TOKEN` env value to the token from Craft minus the `Authorization: Bearer` part.). I'd already enabled **Allow discovery of sourcing data for Gatsby** for my schema.

Could it be anything to do with the version of Gatsby? I'm using version 2.25.3.

**Comment by mattstein** [comment]
> Could it be anything to do with the version of Gatsby? I'm using version 2.25.3.

Shouldn’t be; that’s what this project is using and I’m running it locally just fine.

1. Can you successfully query Craft’s GraphQL API directly using GraphQL Playground or Insomnia or a third-party client?
2. If so, have you also added homepage content and a few test blog posts?

The errors you listed are what I’m used to seeing when the GraphQL connection is busted and nothing is sourced from the Craft site—are those preceded by anything else revealing?

**Comment by sijones-uk** [comment]
Yes, I've got home page content and two blog posts. I've tested the Craft Blog API endpoint using Postman with the following simple query:

```
query MyQuery {
  entries {
    id
    title
  }
}
```

This produced the expected output:

```
{
    "data": {
        "entries": [
            {
                "id": "53",
                "title": "Another blog entry"
            },
            {
                "id": "39",
                "title": "My new blog post"
            },
            {
                "id": "1",
                "title": "About"
            },
            {
                "id": "3",
                "title": "Home"
            }
        ]
    }
}
```

The output from `gatsby develop` starts like this:

```
error There was an error in your GraphQL query:

Cannot query field "allCraftBlogBlogEntry" on type "Query".

If you don't expect "allCraftBlogBlogEntry" to exist on the type "Query" it is most likely a typo.
However, if you expect "allCraftBlogBlogEntry" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allCraftBlogBlogEntry" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error "gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot query field "allCraftBlogBlogEntry" on type "Query".

[...]
```

**Comment by mattstein** [comment]
It _looks_ like everything’s right. If you haven’t already, be sure to run `gatsby clean` and try building again to rule out a cache problem. (I’m reaching here, but that could also be it 🤞.)

**Comment by sijones-uk** [comment]
I've found the cause of this issue: Gatsby wasn't liking my self-signed certificate. When I changed the `CRAFTGQL_URL` to use `http` instead, the above errors stopped. I'm now getting a different error, essentially the same as [the issue reported here](https://github.com/craftcms/gatsby-source-craft/issues/5) (but unlike that issue, I've already got content in the site, so that wasn't the cause):

```
error "gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Variable "$id" is not defined

  379 |     if (remoteConfigVersion !== localConfigVersion || !localContentUpdateTime) {
  380 |         reporter.info("Cached content is unavailable or outdated, sourcing _all_ nodes.");
> 381 |         await sourceAllNodes(config);
      |         ^
  382 |     }
  383 |     else {
  384 |         reporter.info(`Craft config version has not changed since last sourcing. Checking for content changes since "${localContentUpdateTime}".`);

Make sure that you don't have a typo somewhere and use valid arguments in sourceNodes lifecycle.
Learn more about sourceNodes here: https://www.gatsbyjs.org/docs/node-apis/#sourceNodes
```

I'm assuming this isn't related to the Starter Blog specifically, so will need to open a new issue in the Gatsby source plugin repo?

**Comment by mattstein** [comment]
That looks like the error you’d get when your GraphQL schema isn’t configured correctly on the Craft end. With the Starter Blog it can happen if you’ve not added entries or content, and I saw the same thing testing earlier when I forgot to enable _Users_ for said schema.

Make sure your schema’s sufficiently permissive, has that **Allow discovery of sourcing data for Gatsby** option enabled, and that you’ve run `gatsby clean` before trying `gatsby develop` again. I apologize if I sound like a broken record, but it seems as though some environmental setting or configuration is not right.

**Comment by sijones-uk** [comment]
> I saw the same thing testing earlier when I forgot to enable Users for said schema

That was it - thank you! I hadn't checked the "View all users" box in my schema because the Gatsby components and pages aren't outputting any user info. Do you know why it fails when that box is unchecked?

**Comment by mattstein** [comment]
Aha! I’m glad you’ve got it working. Every entry has an author, which is of course a user. I’ll let @andris-sevcenko decide what to do with this information.

**Comment by mattstein** [comment]
Actually nevermind—that bug’s been fixed for the next upcoming Gatsby Helper release. Closing this out!
