### ISSUE TITLE
Hot reload templates?

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/starter-blog#8]
Hi,
I've used Mix a little bit in the past but don't fully understand the webpack config yet. So I wonder if you can help me with something.

Is it possible to get the html templates to hot reload in the same way as the scss files?

Many thanks

**Comment by andrewfairlie** [comment]
Hi Pete!

This isn't really an answer in the context of this starter blog because I don't think it uses Mix but on our sites where we use Laravel Mix and BrowserSync (I think it's built in to Mix) which sets up a proxy URL (usually localhost:3000) and watches for files (in this case `./templates/**/*.twig`)

```
    .browserSync({
        proxy: process.env.DEFAULT_SITE_URL,
        files: ["./templates/**/*.twig"],
        notify: false,
    })
```

Then if you access your dev site through the proxy URL it'll refresh the page whenever the Twig changes. Not quite hot reloading, but pretty close.

Cheers,

**Comment by fantasticmachine** [comment]
Hi Andrew,

Sorry, I confused matters by mentioning Mix. Not using Mix with this but they both use Webpack so thought it might be relevant (it’s not!)

I was really wondering if there was a way to modify the Webpack config on this starter project to also hot-reload when modifying html and twig templates.

Cheers
Pete

**Comment by bigskillet** [comment]
Hey @fantasticmachine 

The hot-reload, webpack-dev-server in this setup is not working for me either. I've been searching for over a year now, trying to find a way to get webpack-dev-server to refresh when working with Craft, but no luck. I've seen many repos claiming to have solved the problem, but their examples never work. I've been using Browsersync while I search for a cure.

From what I understand, there's an issue [refreshing files outside of the bundle path](https://stenvdb.be/articles/how-to-live-reload-webpack-dev-server-when-saving-external-files), but I'm not having any luck watching the bundle files either! Nothing refreshes! 

If you happen to find a solution for this in the future, I would love to hear about it!

**Comment by mattstein** [comment]
Just updated the webpack config to watch the templates folder and refresh the browser when anything changes. (Changes aren’t _injected_ like JavaScript and styles, but I don’t believe that’s possible with Twig.)
